apiVersion: v1
kind: PersistentVolume
metadata:
  name: text-processor-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/vedarishikareddynalla/home/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: text-processor-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-processor-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: text-processor
  template:
    metadata:
      labels:
        app: text-processor
    spec:
      containers:
      - name: text-processor
        image: text-processor:latest
        volumeMounts:
        - name: data-volume
          mountPath: /home/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: text-processor-pvc

